name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Run only when a new version tag is pushed
  pull_request: # Also run on pull requests for CI
    branches:
      - main

jobs:
  # Job for testing builds on Pull Requests
  test-build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.x'
      - name: Run Go Tidy
        run: go mod tidy
      - name: Test Build
        run: go build -v ./wavelog-gate.go

  # Job for creating a release
  goreleaser:
    if: startsWith(github.ref, 'refs/tags/v') # Only run for tags
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create the release
      packages: write # Needed to publish packages (if any)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all history so GoReleaser can build the changelog
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.x'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # Use the .goreleaser.yml file from the repo
          distribution: goreleaser
          # Run the 'release' command
          args: release --clean
        env:
          # This token is provided by GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
